version: '3.8'

services:
  # ---------------------------------------------------------
  # LAYER 1: FOUNDATION (Database & Discovery)
  # ---------------------------------------------------------
  mysql:
    image: mysql:8.3
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: authdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: app123
    ports:
      - "3306:3306"
    mem_limit: 600m
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    networks:
      - bank-network

  discovery-server:
    build: ../discovery-server_Eureka
    image: discovery-server:latest
    container_name: discovery-server
    restart: always
    ports:
      - "8761:8761"
    volumes:
      - ./logs:/logs
    environment:
      - SPRING_APPLICATION_NAME=discovery-server # for Logging
    deploy:
      resources:
        limits:
          memory: 300M
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8761/actuator/health || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 40s
    networks:
      - bank-network

  # ---------------------------------------------------------
  # LAYER 2: CONFIGURATION VAULT
  # ---------------------------------------------------------
  config-server:
    build: ../spring-cloud-config
    image: config-server:latest
    container_name: config-server
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - ./logs:/logs
    mem_limit: 350m
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
      - SPRING_APPLICATION_NAME=config-server # for logging
    depends_on:
      discovery-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8888/actuator/health || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 40s
    networks:
      - bank-network

  # ---------------------------------------------------------
  # LAYER 3: BUSINESS MICROSERVICES
  # ---------------------------------------------------------
  auth-service:
    build: ../auth-service
    image: auth-service:latest
    container_name: auth-service
    restart: always
    ports:
      - "8084:8084"
    volumes:
      - ./logs:/logs
    mem_limit: 350m
    environment:
      - DB_HOST=mysql
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      # 👇 CRITICAL: Tell the service to wait for and connect to the Config Server
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_APPLICATION_NAME=auth-service # for logging
    depends_on:
      mysql:
        condition: service_healthy
      config-server:
        condition: service_healthy
    networks:
      - bank-network

  customer-service:
    build: ../customer-service
    image: customer-service:latest
    container_name: customer-service
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - ./logs:/logs # Docker creates loan-service.log and customer-service.log here
    mem_limit: 350m
    environment:
      - DB_HOST=mysql
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_APPLICATION_NAME=customer-service # for logging
    depends_on:
      mysql:
        condition: service_healthy
      config-server:
        condition: service_healthy
    networks:
      - bank-network

  loan-service:
    build: ../loan-service
    image: loan-service:latest
    container_name: loan-service
    restart: always
    ports:
      - "8082:8082"
    volumes:
      - ./logs:/logs # All services mount to the SAME local folder
    mem_limit: 350m
    environment:
      - DB_HOST=mysql
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_APPLICATION_NAME=loan-service # for logging
    depends_on:
      mysql:
        condition: service_healthy
      config-server:
        condition: service_healthy
    networks:
      - bank-network

  api-gateway:
    build: ../api-gateway
    image: api-gateway:latest
    container_name: api-gateway
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/logs
    mem_limit: 250m
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_APPLICATION_NAME=api-gateway # for logging
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - bank-network

  # ---------------------------------------------------------
  # LAYER 4: OBSERVABILITY (Grafana / Tempo / OTEL)
  # ---------------------------------------------------------
  tempo:
    image: grafana/tempo:2.2.0
    container_name: tempo
    command: ["-config.file=/etc/tempo.yml"]
    volumes:
      - ./tempo.yml:/etc/tempo.yml
      - ./tempo-data:/tmp/tempo
    ports:
      - "3200:3200"
    mem_limit: 200m
    restart: always
    networks:
      - bank-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "4001:3000"
    mem_limit: 150m
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - bank-network

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317"
      - "4318:4318"
    mem_limit: 150m
    restart: always
    depends_on:
      tempo:
        condition: service_started
    networks:
      - bank-network

networks:
  bank-network:
    driver: bridge

volumes:
  mysql-data:
  grafana-data: