server:
  port: 8084

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://${DB_HOST:mysql}:3306/authdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: appuser
    password: app123

  datasource.hikari:
    connection-timeout: 30000
    maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

#For Tracing
management:
  tracing:
    sampling:
      probability: 1.0

  otlp:
    tracing:
      endpoint: http://otel-collector:4318/v1/traces
