# ===================================================================
# AUTH SERVICE - LOCAL BOOTSTRAP INITIALIZER
# ===================================================================
spring:
  application:
    # 1. This EXACTLY matches the GitHub file name prefix
    name: auth-service

  profiles:
    # 2. Tells the Config Server to grab 'auth-service-dev.yml'
    active: dev

  config:
    # 3. Instructs Spring to pause boot and download settings from port 8888
    import: "optional:configserver:http://localhost:8888"