server:
  port: 8888 # 8888 is the global standard port for Spring Cloud Config Server

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          # 👇 Replace with the HTTPS URL of your newly created GitHub config repository
          uri: https://github.com/Kamalkantkumar/banking-config-repo.git
          default-label: main
          # 👇 YOU MUST ADD THESE TWO LINES FOR PRIVATE REPOSITORIES
          username: Kamalkantkumar
          # 👇 Paste the Personal Access Token (PAT) here!-04-july-2026
<<<<<<< HEAD
          password:
=======
          password: #
>>>>>>> 9dd50cb (feat(logging): implement structured JSON logging and file-based rotation)
          # If your repository is Private, you MUST provide your GitHub credentials here
          # username: your-github-email@gmail.com
          # password: your-github-personal-access-token

# Register with your existing Eureka Server so other microservices can find the Config Server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# To decrypt the {cipher} passwords in GitHub, the Config Server needs a master decryption key
# (In a real bank, this key is injected as a system environment variable, not hardcoded)
encrypt:
  key: "ICICI_BANK_MASTER_DECRYPTION_KEY_2026"