# ===================================================================
# LOCAL STRAP CONFIGURATION FOR SERVICE INITIALIZATION
# ===================================================================
spring:
  application:
    # This name must EXACTLY match the file prefix inside your GitHub config repository
    name: loan-service

  profiles:
    # 👇 Toggle between 'dev' and 'prod' to change configurations instantly without modifying code
    active: dev

  config:
    # Instructs Spring Boot to contact the Config Server registry endpoint during the bootstrap sequence
    import: "optional:configserver:http://localhost:8888"